name: Pre-Deploy Updates Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fetch and override deploy branch
        run: |
          git checkout main
          git pull

          git branch -D deploy || true
          git checkout -b deploy

      - name: Write redirects
        run: |
          python scripts/write_redirects.py

      - name: Add confirm message
        run: |
          echo "Ready to deploy!" 

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔖 Updated update server
          commit_user_name: Zen Browser Robot
          commit_user_email: zen-browser-auto@users.noreply.github.com
          branch: deploy
          push_options: '--force'
